# Generated by Django 6.0.5 on 2026-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('popup', 'Popup'), ('video', 'Video')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='ads/videos/')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False)),
                ('show_on_video_details', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
